In [107]:
import pandas as pd

## Load dataset

In [108]:
df = pd.read_csv('matches.csv')

## Get row cols of the data

In [109]:
df.shape

(1095, 20)

## Sample give random rows. here 10 rows.

In [110]:
df.sample(10)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
1019,1359544,2023,Bengaluru,2023-05-21,League,Shubman Gill,"M Chinnaswamy Stadium, Bengaluru",Royal Challengers Bangalore,Gujarat Titans,Gujarat Titans,field,Gujarat Titans,wickets,6.0,198.0,20.0,N,NaN,Nitin Menon,VK Sharma
591,1082605,2017,Delhi,2017-04-15,League,CJ Anderson,Feroz Shah Kotla,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,Delhi Daredevils,runs,51.0,189.0,20.0,N,NaN,YC Barde,Nitin Menon
414,729311,2014,NaN,2014-04-27,League,DR Smith,Sharjah Cricket Stadium,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Chennai Super Kings,wickets,5.0,146.0,20.0,N,NaN,AK Chaudhary,VA Kulkarni
221,501245,2011,Kolkata,2011-05-07,League,Iqbal Abdulla,Eden Gardens,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,bat,Kolkata Knight Riders,runs,10.0,52.0,10.0,N,D/L,Asad Rauf,PR Reiffel
633,1082648,2017,Bangalore,2017-05-17,Eliminator,NM Coulter-Nile,M Chinnaswamy Stadium,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,7.0,48.0,6.0,N,D/L,AK Chaudhary,Nitin Menon
861,1254089,2021,Abu Dhabi,2021-10-02,League,RD Gaikwad,"Zayed Cricket Stadium, Abu Dhabi",Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,7.0,190.0,20.0,N,NaN,CB Gaffaney,VK Sharma
187,501210,2011,Mumbai,2011-04-15,League,BB McCullum,Wankhede Stadium,Mumbai Indians,Kochi Tuskers Kerala,Kochi Tuskers Kerala,field,Kochi Tuskers Kerala,wickets,8.0,183.0,20.0,N,NaN,BR Doctrove,PR Reiffel
613,1082628,2017,Mumbai,2017-05-01,League,RG Sharma,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Mumbai Indians,wickets,5.0,163.0,20.0,N,NaN,AK Chaudhary,CB Gaffaney
679,1136604,2018,Indore,2018-05-12,League,SP Narine,Holkar Cricket Stadium,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,field,Kolkata Knight Riders,runs,31.0,246.0,20.0,N,NaN,CK Nandan,VK Sharma
398,729279,2014,Abu Dhabi,2014-04-16,League,JH Kallis,Sheikh Zayed Stadium,Mumbai Indians,Kolkata Knight Riders,Kolkata Knight Riders,bat,Kolkata Knight Riders,runs,41.0,164.0,20.0,N,NaN,M Erasmus,RK Illingworth

## All the columns present in the data

In [111]:
df.columns.tolist()

['id',
 'season',
 'city',
 'date',
 'match_type',
 'player_of_match',
 'venue',
 'team1',
 'team2',
 'toss_winner',
 'toss_decision',
 'winner',
 'result',
 'result_margin',
 'target_runs',
 'target_overs',
 'super_over',
 'method',
 'umpire1',
 'umpire2']

## Get the data types of each columns

In [112]:
df.dtypes

id                   int64
season                 str
city                   str
date                   str
match_type             str
player_of_match        str
venue                  str
team1                  str
team2                  str
toss_winner            str
toss_decision          str
winner                 str
result                 str
result_margin      float64
target_runs        float64
target_overs       float64
super_over             str
method                 str
umpire1                str
umpire2                str
dtype: object

In [113]:
df.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [114]:
df.city.sample(10)

377           Pune
239         Mumbai
951     Chandigarh
45         Chennai
1048        Mumbai
242      Bangalore
534      Hyderabad
258          Delhi
283        Kolkata
589         Rajkot
Name: city, dtype: str

In [115]:
df.id[415]

np.int64(729313)

In [116]:
df['date'] = pd.to_datetime(df['date'], errors='coerce')

In [117]:
df.date

0      2008-04-18
1      2008-04-19
2      2008-04-19
3      2008-04-20
4      2008-04-20
          ...
1090   2024-05-19
1091   2024-05-21
1092   2024-05-22
1093   2024-05-24
1094   2024-05-26
Name: date, Length: 1095, dtype: datetime64[us]

In [118]:
df['year'] = df['date'].dt.year

In [119]:
df['year'].dtype

dtype('int32')

In [120]:
df.dtypes

id                          int64
season                        str
city                          str
date               datetime64[us]
match_type                    str
player_of_match               str
venue                         str
team1                         str
team2                         str
toss_winner                   str
toss_decision                 str
winner                        str
result                        str
result_margin             float64
target_runs               float64
target_overs              float64
super_over                    str
method                        str
umpire1                       str
umpire2                       str
year                        int32
dtype: object

In [121]:
df.method.sample(10)

289     NaN
114     NaN
893     NaN
578     NaN
1046    NaN
766     NaN
822     NaN
54      NaN
551     NaN
340     NaN
Name: method, dtype: str

In [122]:
df['method'] = df['method'].fillna('Normal')

In [123]:
df.method.sample(20)

396     Normal
1060    Normal
1091    Normal
852     Normal
708     Normal
916     Normal
973     Normal
180     Normal
75      Normal
856     Normal
924     Normal
249     Normal
424     Normal
809     Normal
933     Normal
972     Normal
551     Normal
67      Normal
254     Normal
867     Normal
Name: method, dtype: str

In [124]:
df[df['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium    33
Sharjah Cricket Stadium                18
Name: count, dtype: int64

In [125]:
df[df['city'].isnull()]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,year
399,729281,2014,NaN,2014-04-17,League,YS Chahal,Sharjah Cricket Stadium,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,...,Royal Challengers Bangalore,wickets,8.0,146.0,20.0,N,Normal,Aleem Dar,S Ravi,2014
402,729287,2014,NaN,2014-04-19,League,PA Patel,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,...,Royal Challengers Bangalore,wickets,7.0,116.0,20.0,N,Normal,Aleem Dar,AK Chaudhary,2014
403,729289,2014,NaN,2014-04-19,League,JP Duminy,Dubai International Cricket Stadium,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,...,Delhi Daredevils,wickets,4.0,167.0,20.0,N,Normal,Aleem Dar,VA Kulkarni,2014
404,729291,2014,NaN,2014-04-20,League,GJ Maxwell,Sharjah Cricket Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,...,Kings XI Punjab,wickets,7.0,192.0,20.0,N,Normal,BF Bowden,M Erasmus,2014
406,729295,2014,NaN,2014-04-22,League,GJ Maxwell,Sharjah Cricket Stadium,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,...,Kings XI Punjab,runs,72.0,194.0,20.0,N,Normal,M Erasmus,S Ravi,2014
407,729297,2014,NaN,2014-04-23,League,RA Jadeja,Dubai International Cricket Stadium,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,...,Chennai Super Kings,runs,7.0,141.0,20.0,N,Normal,HDPK Dharmasena,RK Illingworth,2014
408,729299,2014,NaN,2014-04-24,League,CA Lynn,Sharjah Cricket Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,Kolkata Knight Riders,runs,2.0,151.0,20.0,N,Normal,Aleem Dar,VA Kulkarni,2014
409,729301,2014,NaN,2014-04-25,League,AJ Finch,Dubai International Cricket Stadium,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,...,Sunrisers Hyderabad,runs,4.0,185.0,20.0,N,Normal,M Erasmus,S Ravi,2014
410,729303,2014,NaN,2014-04-25,League,MM Sharma,Dubai International Cricket Stadium,Chennai Super Kings,Mumbai Indians,Mumbai Indians,...,Chennai Super Kings,wickets,7.0,142.0,20.0,N,Normal,BF Bowden,M Erasmus,2014
413,729309,2014,NaN,2014-04-27,League,M Vijay,Sharjah Cricket Stadium,Delhi Daredevils,Mumbai Indians,Mumbai Indians,...,Delhi Daredevils,wickets,6.0,126.0,20.0,N,Normal,Aleem Dar,VA Kulkarni,2014
414,729311,2014,NaN,2014-04-27,League,DR Smith,Sharjah Cricket Stadium,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,...,Chennai Super Kings,wickets,5.0,146.0,20.0,N,Normal,AK Chaudhary,VA Kulkarni,2014
415,729313,2014,NaN,2014-04-28,League,Sandeep Sharma,Dubai International Cricket Stadium,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,...,Kings XI Punjab,wickets,5.0,125.0,20.0,N,Normal,BF Bowden,S Ravi,2014
417,729317,2014,NaN,2014-04-30,League,B Kumar,Dubai International Cricket Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,...,Sunrisers Hyderabad,runs,15.0,173.0,20.0,N,Normal,HDPK Dharmasena,M Erasmus,2014
757,1216493,2020/21,NaN,2020-09-20,League,MP Stoinis,Dubai International Cricket Stadium,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,...,Delhi Capitals,tie,NaN,158.0,20.0,Y,Normal,AK Chaudhary,Nitin Menon,2020
758,1216534,2020/21,NaN,2020-09-21,League,YS Chahal,Dubai International Cricket Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,...,Royal Challengers Bangalore,runs,10.0,164.0,20.0,N,Normal,AY Dandekar,Nitin Menon,2020
759,1216496,2020/21,NaN,2020-09-22,League,SV Samson,Sharjah Cricket Stadium,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,...,Rajasthan Royals,runs,16.0,217.0,20.0,N,Normal,C Shamshuddin,VA Kulkarni,2020
761,1216510,2020/21,NaN,2020-09-24,League,KL Rahul,Dubai International Cricket Stadium,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,...,Kings XI Punjab,runs,97.0,207.0,20.0,N,Normal,AK Chaudhary,PR Reiffel,2020
762,1216539,2020/21,NaN,2020-09-25,League,PP Shaw,Dubai International Cricket Stadium,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,...,Delhi Capitals,runs,44.0,176.0,20.0,N,Normal,KN Ananthapadmanabhan,RK Illingworth,2020
764,1216527,2020/21,NaN,2020-09-27,League,SV Samson,Sharjah Cricket Stadium,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,...,Rajasthan Royals,wickets,4.0,224.0,20.0,N,Normal,RK Illingworth,K Srinivasan,2020
765,1216547,2020/21,NaN,2020-09-28,League,AB de Villiers,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,...,Royal Challengers Bangalore,tie,NaN,202.0,20.0,Y,Normal,Nitin Menon,PR Reiffel,2020
767,1216504,2020/21,NaN,2020-09-30,League,Shivam Mavi,Dubai International Cricket Stadium,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,...,Kolkata Knight Riders,runs,37.0,175.0,20.0,N,Normal,KN Ananthapadmanabhan,C Shamshuddin,2020
769,1216516,2020/21,NaN,2020-10-02,League,PK Garg,Dubai International Cricket Stadium,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,...,Sunrisers Hyderabad,runs,7.0,165.0,20.0,N,Normal,AK Chaudhary,PR Reiffel,2020
771,1216515,2020/21,NaN,2020-10-03,League,SS Iyer,Sharjah Cricket Stadium,Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,...,Delhi Capitals,runs,18.0,229.0,20.0,N,Normal,VA Kulkarni,RK Illingworth,2020
772,1216513,2020/21,NaN,2020-10-04,League,SR Watson,Dubai International Cricket Stadium,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab,...,Chennai Super Kings,wickets,10.0,179.0,20.0,N,Normal,AY Dandekar,Nitin Menon,2020
773,1216538,2020/21,NaN,2020-10-04,League,TA Boult,Sharjah Cricket Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,...,Mumbai Indians,runs,34.0,209.0,20.0,N,Normal,KN Ananthapadmanabhan,RK Illingworth,2020
774,1216519,2020/21,NaN,2020-10-05,League,AR Patel,Dubai International Cricket Stadium,Delhi Capitals,Royal Challengers Bangalore,Royal Challengers Bangalore,...,Delhi Capitals,runs,59.0,197.0,20.0,N,Normal,Nitin Menon,YC Barde,2020
777,1216542,2020/21,NaN,2020-10-08,League,JM Bairstow,Dubai International Cricket Stadium,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,...,Sunrisers Hyderabad,runs,69.0,202.0,20.0,N,Normal,AK Chaudhary,Nitin Menon,2020
778,1216500,2020/21,NaN,2020-10-09,League,R Ashwin,Sharjah Cricket Stadium,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,...,Delhi Capitals,runs,46.0,185.0,20.0,N,Normal,KN Ananthapadmanabhan,C Shamshuddin,2020
780,1216525,2020/21,NaN,2020-10-10,League,V Kohli,Dubai International Cricket Stadium,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,...,Royal Challengers Bangalore,runs,37.0,170.0,20.0,N,Normal,AK Chaudhary,PR Reiffel,2020
781,1216507,2020/21,NaN,2020-10-11,League,R Tewatia,Dubai International Cricket Stadium,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,...,Rajasthan Royals,wickets,5.0,159.0,20.0,N,Normal,YC Barde,PR Reiffel,2020
783,1216540,2020/21,NaN,2020-10-12,League,AB de Villiers,Sharjah Cricket Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,Royal Challengers Bangalore,runs,82.0,195.0,20.0,N,Normal,RK Illingworth,K Srinivasan,2020
784,1216528,2020/21,NaN,2020-10-13,League,RA Jadeja,Dubai International Cricket Stadium,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,...,Chennai Super Kings,runs,20.0,168.0,20.0,N,Normal,AK Chaudhary,PR Reiffel,2020
785,1216543,2020/21,NaN,2020-10-14,League,A Nortje,Dubai International Cricket Stadium,Delhi Capitals,Rajasthan Royals,Delhi Capitals,...,Delhi Capitals,runs,13.0,162.0,20.0,N,Normal,AK Chaudhary,Nitin Menon,2020
786,1216531,2020/21,NaN,2020-10-15,League,KL Rahul,Sharjah Cricket Stadium,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,...,Kings XI Punjab,wickets,8.0,172.0,20.0,N,Normal,KN Ananthapadmanabhan,C Shamshuddin,2020
788,1216509,2020/21,NaN,2020-10-17,League,S Dhawan,Sharjah Cricket Stadium,Chennai Super Kings,Delhi Capitals,Chennai Super Kings,...,Delhi Capitals,wickets,5.0,180.0,20.0,N,Normal,KN Ananthapadmanabhan,RK Illingworth,2020
789,1216522,2020/21,NaN,2020-10-17,League,AB de Villiers,Dubai International Cricket Stadium,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,...,Royal Challengers Bangalore,wickets,7.0,178.0,20.0,N,Normal,AK Chaudhary,Nitin Menon,2020
791,1216517,2020/21,NaN,2020-10-18,League,KL Rahul,Dubai International Cricket Stadium,Mumbai Indians,Kings XI Punjab,Mumbai Indians,...,Kings XI Punjab,tie,NaN,177.0,20.0,Y,Normal,Nitin Menon,PR Reiffel,2020
793,1216546,2020/21,NaN,2020-10-20,League,S Dhawan,Dubai International Cricket Stadium,Delhi Capitals,Kings XI Punjab,Delhi Capitals,...,Kings XI Punjab,wickets,5.0,165.0,20.0,N,Normal,C Shamshuddin,RK Illingworth,2020
795,1216518,2020/21,NaN,2020-10-22,League,MK Pandey,Dubai International Cricket Stadium,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,...,Sunrisers Hyderabad,wickets,8.0,155.0,20.0,N,Normal,Nitin Menon,PR Reiffel,2020
796,1216521,2020/21,NaN,2020-10-23,League,TA Boult,Sharjah Cricket Stadium,Chennai Super Kings,Mumbai Indians,Mumbai Indians,...,Mumbai Indians,wickets,10.0,115.0,20.0,N,Normal,C Shamshuddin,VA Kulkarni,2020
798,1216498,2020/21,NaN,2020-10-24,League,CJ Jordan,Dubai International Cricket Stadium,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,...,Kings XI Punjab,runs,12.0,127.0,20.0,N,Normal,AY Dandekar,PR Reiffel,2020
800,1216544,2020/21,NaN,2020-10-25,League,RD Gaikwad,Dubai International Cricket Stadium,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,...,Chennai Super Kings,wickets,8.0,146.0,20.0,N,Normal,C Shamshuddin,RK Illingworth,2020
801,1216520,2020/21,NaN,2020-10-26,League,CH Gayle,Sharjah Cricket Stadium,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,...,Kings XI Punjab,wickets,8.0,150.0,20.0,N,Normal,KN Ananthapadmanabhan,RK Illingworth,2020
802,1216524,2020/21,NaN,2020-10-27,League,WP Saha,Dubai International Cricket Stadium,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,...,Sunrisers Hyderabad,runs,88.0,220.0,20.0,N,Normal,AK Chaudhary,Nitin Menon,2020
804,1216536,2020/21,NaN,2020-10-29,League,RD Gaikwad,Dubai International Cricket Stadium,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,...,Chennai Super Kings,wickets,6.0,173.0,20.0,N,Normal,C Shamshuddin,RK Illingworth,2020
806,1216502,2020/21,NaN,2020-10-31,League,Sandeep Sharma,Sharjah Cricket Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,...,Sunrisers Hyderabad,wickets,5.0,121.0,20.0,N,Normal,KN Ananthapadmanabhan,K Srinivasan,2020
807,1216535,2020/21,NaN,2020-10-31,League,Ishan Kishan,Dubai International Cricket Stadium,Delhi Capitals,Mumbai Indians,Mumbai Indians,...,Mumbai Indians,wickets,9.0,111.0,20.0,N,Normal,YC Barde,PR Reiffel,2020
809,1216530,2020/21,NaN,2020-11-01,League,PJ Cummins,Dubai International Cricket Stadium,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,...,Kolkata Knight Riders,runs,60.0,192.0,20.0,N,Normal,Nitin Menon,PR Reiffel,2020
811,1216495,2020/21,NaN,2020-11-03,League,S Nadeem,Sharjah Cricket Stadium,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad,...,Sunrisers Hyderabad,wickets,10.0,150.0,20.0,N,Normal,C Shamshuddin,RK Illingworth,2020
812,1237177,2020/21,NaN,2020-11-05,Qualifier 1,JJ Bumrah,Dubai International Cricket Stadium,Mumbai Indians,Delhi Capitals,Delhi Capitals,...,Mumbai Indians,runs,57.0,201.0,20.0,N,Normal,CB Gaffaney,Nitin Menon,2020
815,1237181,2020/21,NaN,2020-11-10,Final,TA Boult,Dubai International Cricket Stadium,Delhi Capitals,Mumbai Indians,Delhi Capitals,...,Mumbai Indians,wickets,5.0,157.0,20.0,N,Normal,CB Gaffaney,Nitin Menon,2020

## dropping rows

In [126]:
df = df.dropna(subset=['city'])

In [127]:
df.columns.tolist()

['id',
 'season',
 'city',
 'date',
 'match_type',
 'player_of_match',
 'venue',
 'team1',
 'team2',
 'toss_winner',
 'toss_decision',
 'winner',
 'result',
 'result_margin',
 'target_runs',
 'target_overs',
 'super_over',
 'method',
 'umpire1',
 'umpire2',
 'year']

## Drop Columns

In [128]:
df = df.drop(columns=['umpire1', 'umpire2', 'player_of_match'])

In [129]:
df.shape

(1044, 18)

In [130]:
df.isnull().sum()

id                0
season            0
city              0
date              0
match_type        0
venue             0
team1             0
team2             0
toss_winner       0
toss_decision     0
winner            5
result            0
result_margin    16
target_runs       3
target_overs      3
super_over        0
method            0
year              0
dtype: int64

In [131]:
df[df['winner'].isnull()]

,id,season,city,date,match_type,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,year
241,501265,2011,Delhi,2011-05-21,League,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,no result,NaN,NaN,NaN,N,Normal,2011
485,829763,2015,Bangalore,2015-04-29,League,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,NaN,NaN,N,Normal,2015
511,829813,2015,Bangalore,2015-05-17,League,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,no result,NaN,188.0,20.0,N,Normal,2015
744,1178424,2019,Bengaluru,2019-04-30,League,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,63.0,5.0,N,Normal,2019
994,1359519,2023,Lucknow,2023-05-03,League,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,NaN,no result,NaN,NaN,NaN,N,Normal,2023

## Dropping rows

In [132]:
df = df.dropna(subset=['winner'])

In [133]:
df = df.dropna(subset=['result_margin'])

In [134]:
df = df.dropna(subset=['target_runs', 'target_overs'])

In [135]:
df.shape

(1028, 18)

In [136]:
df.isnull().sum()

id               0
season           0
city             0
date             0
match_type       0
venue            0
team1            0
team2            0
toss_winner      0
toss_decision    0
winner           0
result           0
result_margin    0
target_runs      0
target_overs     0
super_over       0
method           0
year             0
dtype: int64

## Unique values

In [137]:
df['team1'].unique().tolist()

['Royal Challengers Bangalore',
 'Kings XI Punjab',
 'Delhi Daredevils',
 'Mumbai Indians',
 'Kolkata Knight Riders',
 'Rajasthan Royals',
 'Deccan Chargers',
 'Chennai Super Kings',
 'Kochi Tuskers Kerala',
 'Pune Warriors',
 'Sunrisers Hyderabad',
 'Gujarat Lions',
 'Rising Pune Supergiants',
 'Rising Pune Supergiant',
 'Delhi Capitals',
 'Punjab Kings',
 'Lucknow Super Giants',
 'Gujarat Titans',
 'Royal Challengers Bengaluru']

In [138]:
df['venue'].unique().tolist()

['M Chinnaswamy Stadium',
 'Punjab Cricket Association Stadium, Mohali',
 'Feroz Shah Kotla',
 'Wankhede Stadium',
 'Eden Gardens',
 'Sawai Mansingh Stadium',
 'Rajiv Gandhi International Stadium, Uppal',
 'MA Chidambaram Stadium, Chepauk',
 'Dr DY Patil Sports Academy',
 'Newlands',
 "St George's Park",
 'Kingsmead',
 'SuperSport Park',
 'Buffalo Park',
 'New Wanderers Stadium',
 'De Beers Diamond Oval',
 'OUTsurance Oval',
 'Brabourne Stadium',
 'Sardar Patel Stadium, Motera',
 'Barabati Stadium',
 'Brabourne Stadium, Mumbai',
 'Vidarbha Cricket Association Stadium, Jamtha',
 'Himachal Pradesh Cricket Association Stadium',
 'Nehru Stadium',
 'Holkar Cricket Stadium',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
 'Subrata Roy Sahara Stadium',
 'Maharashtra Cricket Association Stadium',
 'Shaheed Veer Narayan Singh International Stadium',
 'JSCA International Stadium Complex',
 'Sheikh Zayed Stadium',
 'Punjab Cricket Association IS Bindra Stadium, Mohali',
 'Saurashtra Cricket Association Stadium',
 'Green Park',
 'M.Chinnaswamy Stadium',
 'Punjab Cricket Association IS Bindra Stadium',
 'Rajiv Gandhi International Stadium',
 'MA Chidambaram Stadium',
 'Arun Jaitley Stadium',
 'MA Chidambaram Stadium, Chepauk, Chennai',
 'Wankhede Stadium, Mumbai',
 'Narendra Modi Stadium, Ahmedabad',
 'Arun Jaitley Stadium, Delhi',
 'Dubai International Cricket Stadium',
 'Zayed Cricket Stadium, Abu Dhabi',
 'Sharjah Cricket Stadium',
 'Dr DY Patil Sports Academy, Mumbai',
 'Maharashtra Cricket Association Stadium, Pune',
 'Eden Gardens, Kolkata',
 'Punjab Cricket Association IS Bindra Stadium, Mohali, Chandigarh',
 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow',
 'Rajiv Gandhi International Stadium, Uppal, Hyderabad',
 'M Chinnaswamy Stadium, Bengaluru',
 'Barsapara Cricket Stadium, Guwahati',
 'Sawai Mansingh Stadium, Jaipur',
 'Himachal Pradesh Cricket Association Stadium, Dharamsala',
 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium, Visakhapatnam']

In [139]:
df['season'].unique().tolist()

['2007/08',
 '2009',
 '2009/10',
 '2011',
 '2012',
 '2013',
 '2014',
 '2015',
 '2016',
 '2017',
 '2018',
 '2019',
 '2020/21',
 '2021',
 '2022',
 '2023',
 '2024']

In [140]:
df.sample(10)

,id,season,city,date,match_type,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,year
87,392212,2009,Centurion,2009-05-06,League,SuperSport Park,Deccan Chargers,Mumbai Indians,Deccan Chargers,bat,Deccan Chargers,runs,19.0,146.0,20.0,N,Normal,2009
74,392199,2009,Durban,2009-04-29,League,Kingsmead,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders,bat,Royal Challengers Bangalore,wickets,5.0,140.0,20.0,N,Normal,2009
367,598042,2013,Pune,2013-05-02,League,Subrata Roy Sahara Stadium,Pune Warriors,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,17.0,188.0,20.0,N,Normal,2013
710,1175370,2019,Mumbai,2019-04-03,League,Wankhede Stadium,Mumbai Indians,Chennai Super Kings,Chennai Super Kings,field,Mumbai Indians,runs,37.0,171.0,20.0,N,Normal,2019
633,1082648,2017,Bangalore,2017-05-17,Eliminator,M Chinnaswamy Stadium,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,7.0,48.0,6.0,N,D/L,2017
1060,1426275,2024,Mohali,2024-04-21,League,Maharaja Yadavindra Singh International Cricke...,Punjab Kings,Gujarat Titans,Punjab Kings,bat,Gujarat Titans,wickets,3.0,143.0,20.0,N,Normal,2024
51,336036,2007/08,Jaipur,2008-05-26,League,Sawai Mansingh Stadium,Rajasthan Royals,Mumbai Indians,Rajasthan Royals,field,Rajasthan Royals,wickets,5.0,146.0,20.0,N,Normal,2008
336,598011,2013,Mumbai,2013-04-13,League,Wankhede Stadium,Mumbai Indians,Pune Warriors,Mumbai Indians,bat,Mumbai Indians,runs,41.0,184.0,20.0,N,Normal,2013
494,829781,2015,Kolkata,2015-05-04,League,Eden Gardens,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kolkata Knight Riders,runs,35.0,168.0,20.0,N,Normal,2015
472,829735,2015,Ahmedabad,2015-04-19,League,"Sardar Patel Stadium, Motera",Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,bat,Rajasthan Royals,wickets,8.0,157.0,20.0,N,Normal,2015

## Fix team names

In [141]:
team_fix = {
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru',
    'Rising Pune Supergiants': 'Rising Pune Supergiant',
    'Deccan Chargers': 'Sunrisers Hyderabad'
}

for col in ['team1', 'team2', 'toss_winner', 'winner']:
    df[col] = df[col].replace(team_fix)

In [142]:
df.sample(10)

,id,season,city,date,match_type,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,year
890,1304061,2022,Mumbai,2022-04-07,League,"Dr DY Patil Sports Academy, Mumbai",Delhi Capitals,Lucknow Super Giants,Lucknow Super Giants,field,Lucknow Super Giants,wickets,6.0,150.0,20.0,N,Normal,2022
1058,1426273,2024,Delhi,2024-04-20,League,"Arun Jaitley Stadium, Delhi",Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Sunrisers Hyderabad,runs,67.0,267.0,20.0,N,Normal,2024
898,1304069,2022,Pune,2022-04-13,League,"Maharashtra Cricket Association Stadium, Pune",Punjab Kings,Mumbai Indians,Mumbai Indians,field,Punjab Kings,runs,12.0,199.0,20.0,N,Normal,2022
853,1254098,2021,Abu Dhabi,2021-09-26,League,"Zayed Cricket Stadium, Abu Dhabi",Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,bat,Chennai Super Kings,wickets,2.0,172.0,20.0,N,Normal,2021
984,1359509,2023,Ahmedabad,2023-04-25,League,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Mumbai Indians,Mumbai Indians,field,Gujarat Titans,runs,55.0,208.0,20.0,N,Normal,2023
388,598028,2013,Dharamsala,2013-05-16,League,Himachal Pradesh Cricket Association Stadium,Punjab Kings,Delhi Capitals,Delhi Capitals,field,Punjab Kings,runs,7.0,172.0,20.0,N,Normal,2013
867,1254095,2021,Abu Dhabi,2021-10-06,League,"Zayed Cricket Stadium, Abu Dhabi",Sunrisers Hyderabad,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,Sunrisers Hyderabad,runs,4.0,142.0,20.0,N,Normal,2021
652,1136577,2018,Pune,2018-04-20,League,Maharashtra Cricket Association Stadium,Chennai Super Kings,Rajasthan Royals,Rajasthan Royals,field,Chennai Super Kings,runs,64.0,205.0,20.0,N,Normal,2018
817,1254059,2021,Mumbai,2021-04-10,League,"Wankhede Stadium, Mumbai",Chennai Super Kings,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,wickets,7.0,189.0,20.0,N,Normal,2021
2,335984,2007/08,Delhi,2008-04-19,League,Feroz Shah Kotla,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,bat,Delhi Capitals,wickets,9.0,130.0,20.0,N,Normal,2008

In [143]:
df['team1'].unique().tolist()

['Royal Challengers Bengaluru',
 'Punjab Kings',
 'Delhi Capitals',
 'Mumbai Indians',
 'Kolkata Knight Riders',
 'Rajasthan Royals',
 'Sunrisers Hyderabad',
 'Chennai Super Kings',
 'Kochi Tuskers Kerala',
 'Pune Warriors',
 'Gujarat Lions',
 'Rising Pune Supergiant',
 'Lucknow Super Giants',
 'Gujarat Titans']

## Fix venue names

In [146]:
df['venue'] = df['venue'].str.split(',').str[0].str.strip()

In [148]:
venue_fix = {
    'M.Chinnaswamy Stadium': 'M Chinnaswamy Stadium',
    'Punjab Cricket Association Stadium': 'Punjab Cricket Association IS Bindra Stadium',
    'Feroz Shah Kotla': 'Arun Jaitley Stadium',          # renamed 2019
    'Sardar Patel Stadium': 'Narendra Modi Stadium',      # renamed 2021
    'Subrata Roy Sahara Stadium': 'Maharashtra Cricket Association Stadium',
    'Zayed Cricket Stadium': 'Sheikh Zayed Stadium',
    'Brabourne Stadium': 'Brabourne Stadium'
}

df['venue'] = df['venue'].replace(venue_fix)

In [149]:
df.sample(10)

,id,season,city,date,match_type,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,year
903,1304074,2022,Mumbai,2022-04-17,League,Dr DY Patil Sports Academy,Punjab Kings,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,7.0,152.0,20.0,N,Normal,2022
1006,1359531,2023,Mumbai,2023-05-12,League,Wankhede Stadium,Mumbai Indians,Gujarat Titans,Gujarat Titans,field,Mumbai Indians,runs,27.0,219.0,20.0,N,Normal,2023
698,1175358,2019,Mumbai,2019-03-24,League,Wankhede Stadium,Delhi Capitals,Mumbai Indians,Mumbai Indians,field,Delhi Capitals,runs,37.0,214.0,20.0,N,Normal,2019
948,1312199,2022,Ahmedabad,2022-05-27,Qualifier 2,Narendra Modi Stadium,Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,7.0,158.0,20.0,N,Normal,2022
1009,1359534,2023,Jaipur,2023-05-14,League,Sawai Mansingh Stadium,Royal Challengers Bengaluru,Rajasthan Royals,Royal Challengers Bengaluru,bat,Royal Challengers Bengaluru,runs,112.0,172.0,20.0,N,Normal,2023
53,336012,2007/08,Bangalore,2008-05-28,League,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,9.0,123.0,18.0,N,Normal,2008
122,419113,2009/10,Kolkata,2010-03-16,League,Eden Gardens,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,55.0,165.0,20.0,N,Normal,2010
863,1254090,2021,Sharjah,2021-10-03,League,Sharjah Cricket Stadium,Royal Challengers Bengaluru,Punjab Kings,Royal Challengers Bengaluru,bat,Royal Challengers Bengaluru,runs,6.0,165.0,20.0,N,Normal,2021
530,980927,2016,Mumbai,2016-04-20,League,Wankhede Stadium,Mumbai Indians,Royal Challengers Bengaluru,Mumbai Indians,field,Mumbai Indians,wickets,6.0,171.0,20.0,N,Normal,2016
257,548315,2012,Bangalore,2012-04-10,League,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Kolkata Knight Riders,Royal Challengers Bengaluru,field,Kolkata Knight Riders,runs,42.0,166.0,20.0,N,Normal,2012

In [150]:
df['season'] = df['season'].str.split('/').str[0].astype(int)

In [153]:
df.sample(10)

,id,season,city,date,match_type,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,year
600,1082614,2017,Mumbai,2017-04-22,League,Wankhede Stadium,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,14.0,143.0,20.0,N,Normal,2017
523,980913,2016,Delhi,2016-04-15,League,Arun Jaitley Stadium,Delhi Capitals,Punjab Kings,Delhi Capitals,field,Delhi Capitals,wickets,8.0,112.0,20.0,N,Normal,2016
459,829707,2015,Chennai,2015-04-09,League,MA Chidambaram Stadium,Chennai Super Kings,Delhi Capitals,Delhi Capitals,field,Chennai Super Kings,runs,1.0,151.0,20.0,N,Normal,2015
249,548307,2012,Kolkata,2012-04-05,League,Eden Gardens,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,wickets,8.0,98.0,12.0,N,Normal,2012
425,733985,2014,Delhi,2014-05-07,League,Arun Jaitley Stadium,Delhi Capitals,Kolkata Knight Riders,Delhi Capitals,bat,Kolkata Knight Riders,wickets,8.0,161.0,20.0,N,Normal,2014
343,598018,2013,Pune,2013-04-17,League,Maharashtra Cricket Association Stadium,Pune Warriors,Sunrisers Hyderabad,Pune Warriors,field,Sunrisers Hyderabad,runs,11.0,120.0,20.0,N,Normal,2013
560,980987,2016,Bangalore,2016-05-14,League,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Gujarat Lions,Gujarat Lions,field,Royal Challengers Bengaluru,runs,144.0,249.0,20.0,N,Normal,2016
1061,1426276,2024,Jaipur,2024-04-22,League,Sawai Mansingh Stadium,Mumbai Indians,Rajasthan Royals,Mumbai Indians,bat,Rajasthan Royals,wickets,9.0,180.0,20.0,N,Normal,2024
734,1178414,2019,Bengaluru,2019-04-21,League,M Chinnaswamy Stadium,Royal Challengers Bengaluru,Chennai Super Kings,Chennai Super Kings,field,Royal Challengers Bengaluru,runs,1.0,162.0,20.0,N,Normal,2019
75,392200,2009,Durban,2009-04-29,League,Kingsmead,Punjab Kings,Mumbai Indians,Punjab Kings,bat,Punjab Kings,runs,3.0,120.0,20.0,N,Normal,2009

In [154]:
print("Teams :", df['team1'].nunique())
print("Venues:", df['venue'].nunique())
print("Cities:", df['city'].nunique())

Teams : 14
Venues: 36
Cities: 36

In [156]:
print(sorted(df['city'].unique().tolist()))

['Abu Dhabi', 'Ahmedabad', 'Bangalore', 'Bengaluru', 'Bloemfontein', 'Cape Town', 'Centurion', 'Chandigarh', 'Chennai', 'Cuttack', 'Delhi', 'Dharamsala', 'Dubai', 'Durban', 'East London', 'Guwahati', 'Hyderabad', 'Indore', 'Jaipur', 'Johannesburg', 'Kanpur', 'Kimberley', 'Kochi', 'Kolkata', 'Lucknow', 'Mohali', 'Mumbai', 'Nagpur', 'Navi Mumbai', 'Port Elizabeth', 'Pune', 'Raipur', 'Rajkot', 'Ranchi', 'Sharjah', 'Visakhapatnam']

In [158]:
city_fix = {'Bangalore': 'Bengaluru', 'Navi Mumbai': 'Mumbai'}
df['city'] = df['city'].replace(city_fix)
print("Cities now:", df['city'].nunique())

Cities now: 34

## Save in CSV file

In [159]:
df.to_csv('matches_clean.csv', index=False)